const types = {
    GET_CONTACTS: 'GET_CONTACTS',
    CREATE_CONTACT: 'CREATE_CONTACT' ,
    DELETE_CONTACT: 'DELETE_CONTACT',
    UPDATE_CONTACT: 'UPDATE_CONTACT',
    FILL_CONTACT_FIELDS: 'FILL_CONTACT_FIELDS'   
};

export default types;
